#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

mkdir -p build
 
# Build artifacts
MAVEN_OPTS+="-DskipTests -DskipTest -DskipITs "
MAVEN_OPTS+="-Drequire.zstd -Dbundle.zstd -Dzstd.lib=/usr/lib64 "
MAVEN_OPTS+="-Drequire.snappy -Dbundle.snappy=true -Dsnappy.lib=/usr/lib64 "
MAVEN_OPTS+="-Drequire.openssl "

# The Yarn UI and the yarn applications catalog both require a version of node.js which does not work with centos6
# I've removed -Pyarn-ui, and added the below -pl exclusion in order to get around this incompatibility.
# If we end up needing yarn-ui as part of a yarn upgrade, we'll need to investigate building this for centos8 or some
# other more tactical workaround like pinning the node.js to an older version. I tried that with -Dnodejs.version, but that
# failed for other dependencies that expected a particular node version, etc. So a deeper investigation will be necessary.

# Build artifacts
mvn $ANT_OPTS $BUNDLE_SNAPPY \
    -pl '!hadoop-yarn-project/hadoop-yarn/hadoop-yarn-applications/hadoop-yarn-applications-catalog/hadoop-yarn-applications-catalog-webapp' \
    -Pdist -Pnative -Dtar ${MAVEN_OPTS} clean package ${EXTRA_GOALS} "$@"

(cd build ; tar --strip-components=1 -xzvf  ../hadoop-dist/target/hadoop-${HADOOP_VERSION}.tar.gz)

# Create a manifest for hadoop client package
(cd hadoop-client-modules/hadoop-client/target/hadoop-client-*/share/hadoop/client/lib ; ls) > build/hadoop-client.list

cp -r hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfspp/include/hdfspp build/include/
